### ISSUE TITLE
Constants

### ISSUE THREAD

**Issue by LobovVitaliy** [vitalik296/euro_defusion#3]
https://github.com/vitalik296/euro_defusion/blob/c45ffc1d26a8fc491c4b751cc0b1dadb291a24a1/city.py#L11
https://github.com/vitalik296/euro_defusion/blob/c45ffc1d26a8fc491c4b751cc0b1dadb291a24a1/city.py#L37
Please use constant variables

**Comment by vitalik296** [comment]
Constant variable added
